import { useEffect, useRef } from 'react';
import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';

/**
 * Renders a real 3D mesh (.glb generated by TripoSR) with orbit controls so the
 * user can freely rotate / zoom an actual model — not an image turntable.
 * props.glbUrl = object URL (or http URL) to the .glb file.
 */
export default function MeshViewer({ glbUrl }) {
    const mountRef = useRef(null);

    useEffect(() => {
        const mount = mountRef.current;
        if (!mount || !glbUrl) return;

        let W = mount.clientWidth || 400;
        let H = mount.clientHeight || 600;

        const scene = new THREE.Scene();
        const camera = new THREE.PerspectiveCamera(40, W / H, 0.01, 100);
        camera.position.set(0, 0, 2.4);

        const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
        renderer.setSize(W, H);
        renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
        renderer.outputColorSpace = THREE.SRGBColorSpace;
        mount.appendChild(renderer.domElement);
        renderer.domElement.style.touchAction = 'none';

        // Even, soft lighting from a few directions so the mesh reads well.
        scene.add(new THREE.AmbientLight(0xffffff, 1.1));
        const d1 = new THREE.DirectionalLight(0xffffff, 1.0); d1.position.set(1, 1.5, 2); scene.add(d1);
        const d2 = new THREE.DirectionalLight(0xffffff, 0.7); d2.position.set(-1.5, 0.5, -1.5); scene.add(d2);
        const d3 = new THREE.DirectionalLight(0xffffff, 0.5); d3.position.set(0, -1.5, 1); scene.add(d3);

        const controls = new OrbitControls(camera, renderer.domElement);
        controls.enableDamping = true;
        controls.dampingFactor = 0.08;
        // Horizontal (left/right) rotation only, via cursor drag — no auto-spin,
        // no zoom, no pan, and the vertical orbit is locked to eye level.
        controls.autoRotate = false;
        controls.enableZoom = false;
        controls.enablePan = false;
        controls.minPolarAngle = Math.PI / 2;
        controls.maxPolarAngle = Math.PI / 2;

        let model = null;
        const loader = new GLTFLoader();
        loader.load(
            glbUrl,
            (gltf) => {
                model = gltf.scene;
                // center + scale to fit the view
                const box = new THREE.Box3().setFromObject(model);
                const size = box.getSize(new THREE.Vector3());
                const center = box.getCenter(new THREE.Vector3());
                model.position.sub(center);
                const maxDim = Math.max(size.x, size.y, size.z) || 1;
                model.scale.setScalar(1.7 / maxDim);
                // many single-image meshes come in facing away / rolled — leave as-is;
                // orbit lets the user turn it.
                scene.add(model);
            },
            undefined,
            (err) => console.error('Mesh load failed:', err),
        );

        let raf;
        const loop = () => {
            controls.update();
            renderer.render(scene, camera);
            raf = requestAnimationFrame(loop);
        };
        loop();

        const onResize = () => {
            W = mount.clientWidth || W; H = mount.clientHeight || H;
            camera.aspect = W / H; camera.updateProjectionMatrix();
            renderer.setSize(W, H);
        };
        window.addEventListener('resize', onResize);

        return () => {
            cancelAnimationFrame(raf);
            window.removeEventListener('resize', onResize);
            controls.dispose();
            if (model) {
                model.traverse((o) => {
                    if (o.geometry) o.geometry.dispose();
                    if (o.material) {
                        const mats = Array.isArray(o.material) ? o.material : [o.material];
                        mats.forEach((m) => { m.map?.dispose?.(); m.dispose?.(); });
                    }
                });
            }
            renderer.dispose();
            if (renderer.domElement.parentNode) {
                renderer.domElement.parentNode.removeChild(renderer.domElement);
            }
        };
    }, [glbUrl]);

    return <div ref={mountRef} className="w-full h-full" />;
}
